TARGET_ARCH = "arm"
TARGET_PREFIX = "arm-linux-gnueabi-"
KERNEL_DEFCONFIG = "versatile_defconfig"
KERNEL_DEVICETREE = "qemu-versatile-pb.dtb"
QEMU_MACHINE = "versatilepb"
QEMU_MEM = "128"
QEMU_APPEND = "console=ttyAMA0 root=/dev/mmcblk0 rootwait rw"
