BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "distro"
BBFILE_PATTERN_distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_distro = "10"
LAYERDEPENDS_distro = "core bsp"
LAYERSERIES_COMPAT_distro = "bitbaker-1"
